#!/usr/bin/env bash
# Human-only kit setup wizard. Agents must not run this.
# Generated from the wizard skill library (identical above STAGES).

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'EOF'
ask setup — human-only tracker + MCP wizard

Usage: ./ask setup

Refuses when stdin or stdout is not a TTY (agents must not run this).
--help works without a TTY.

Writes gitignored .ask.env and .ask/tracker-context.md.
Writes .ask/tracker.md (type + public URL; safe to commit).
Merges MCP stubs into ~/.cursor/mcp.json using ${env:...} only.
Installs the pinned OpenSpec CLI under ~/.local when node and npm are
on PATH; skips that install with a warning when they are missing.

This repo must already be ask-based (_ask/ and ./ask). Adding the kit
is askit's confirm-to-add step, not this wizard.
EOF
  exit 0
fi

if [[ ! -t 0 || ! -t 1 ]]; then
  echo "setup: human-only. Agents must not run ./ask setup (needs a TTY)." >&2
  echo "setup: use --help, or run it yourself in a terminal." >&2
  exit 2
fi

#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ASK_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ASK_ROOT"
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "setup: not a git repository" >&2
  exit 2
fi
ENV_FILE="$ASK_ROOT/.ask.env"
MCP_JSON="${MCP_JSON:-$HOME/.cursor/mcp.json}"

_remote_https() {
  local raw host path
  raw="$(git remote get-url origin 2>/dev/null || true)"
  [[ -z "$raw" ]] && return 0
  if [[ "$raw" =~ ^git@([^:]+):(.+)$ ]]; then
    host="${BASH_REMATCH[1]}"
    path="${BASH_REMATCH[2]}"
    path="${path%.git}"
    printf 'https://%s/%s' "$host" "$path"
  elif [[ "$raw" =~ ^https?:// ]]; then
    printf '%s' "${raw%.git}"
  fi
}

_merge_mcp_server() {
  local name="$1" spec_json="$2"
  MCP_JSON="$MCP_JSON" MCP_NAME="$name" MCP_SPEC="$spec_json" python3 - <<'PY'
import json, os
from pathlib import Path
path = Path(os.environ["MCP_JSON"])
name = os.environ["MCP_NAME"]
spec = json.loads(os.environ["MCP_SPEC"])
data = {"mcpServers": {}}
if path.exists():
    raw = path.read_text() or "{}"
    data = json.loads(raw)
    if not isinstance(data, dict):
        data = {"mcpServers": {}}
data.setdefault("mcpServers", {})
data["mcpServers"][name] = spec
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(json.dumps(data, indent=2) + "\n")
print(f"  merged MCP server {name} → {path} (no token values written)")
PY
}

_write_tracker_md() {
  local kind="$1" url="$2"
  mkdir -p "$ASK_ROOT/.ask"
  cat > "$ASK_ROOT/.ask/tracker.md" <<EOF
# Tracker

- **type:** ${kind}
- **url:** ${url}

Public only. Secrets live in \`.ask.env\` (gitignored).
EOF
  note "wrote .ask/tracker.md (safe to commit)"
}

_write_tracker_context() {
  mkdir -p "$ASK_ROOT/.ask"
  if [[ ! -f "$ASK_ROOT/.ask/tracker-context.md" ]]; then
    cat > "$ASK_ROOT/.ask/tracker-context.md" <<'EOF'
# Current issue (local; gitignored)

- **epic:**
- **story:**
EOF
    note "wrote .ask/tracker-context.md (gitignored)"
  fi
}

TOTAL_STAGES=5

banner "Ask setup (human-only)"

ASK_TRACKER=""
while true; do
  stage "Choose issue tracker"
  say "gitlab · github · jira · none"
  say "none skips URL and API key; you can only go back and choose again."
  ask ASK_TRACKER "Tracker:"
  ASK_TRACKER="$(printf '%s' "$ASK_TRACKER" | tr '[:upper:]' '[:lower:]')"
  case "$ASK_TRACKER" in
    gitlab|github|jira)
      break
      ;;
    none)
      say "Skipped. The only next step is to choose a tracker."
      if confirm "Choose a tracker now?"; then
        continue
      fi
      warn "No tracker selected. Re-run ./ask setup when you want one."
      write_env ASK_TRACKER "none"
      write_env ASK_TRACKER_URL ""
      _write_tracker_md "none" ""
      break
      ;;
    *)
      warn "Unknown tracker. Use gitlab, github, jira, or none."
      ;;
  esac
done

if [[ "$ASK_TRACKER" != "none" ]]; then
  stage "Tracker address"
  remote="$(_remote_https || true)"
  case "$ASK_TRACKER" in
    jira)
      prefill="${ASK_TRACKER_URL:-https://jira.partcorp.ir/}"
      [[ -z "$(_existing ASK_TRACKER_URL || true)" ]] || prefill="$(_existing ASK_TRACKER_URL)"
      note "Default Jira URL is a Partai prefill; clear or edit it if this is not your host."
      say "Prefill: $prefill"
      ask ASK_TRACKER_URL "Jira URL (Enter uses prefill if empty and none saved):"
      [[ -z "$ASK_TRACKER_URL" ]] && ASK_TRACKER_URL="$prefill"
      write_env ASK_TRACKER "$ASK_TRACKER"
      write_env ASK_TRACKER_URL "$ASK_TRACKER_URL"
      write_env JIRA_URL "$ASK_TRACKER_URL"
      open_url "${ASK_TRACKER_URL%/}/secure/ViewProfile.jspa"
      step "Create or copy a Jira personal access token (or API token)."
      ask_secret JIRA_PERSONAL_TOKEN "Paste the Jira token:"
      write_env JIRA_PERSONAL_TOKEN "$JIRA_PERSONAL_TOKEN"
      _merge_mcp_server mcp-atlassian "$(cat <<'JSON'
{"command":"uvx","args":["mcp-atlassian"],"env":{"JIRA_URL":"${env:JIRA_URL}","JIRA_PERSONAL_TOKEN":"${env:JIRA_PERSONAL_TOKEN}"}}
JSON
)"
      _write_tracker_md jira "$ASK_TRACKER_URL"
      ;;
    github)
      prefill="https://github.com/"
      if [[ "$remote" == *github.com* ]]; then
        prefill="$remote"
      fi
      say "Prefill: $prefill"
      ask ASK_TRACKER_URL "GitHub URL (Enter uses prefill if empty and none saved):"
      [[ -z "$ASK_TRACKER_URL" ]] && ASK_TRACKER_URL="$prefill"
      write_env ASK_TRACKER "$ASK_TRACKER"
      write_env ASK_TRACKER_URL "$ASK_TRACKER_URL"
      open_url "https://github.com/settings/tokens"
      step "Create a PAT with repo issue scopes. Do not paste it into git."
      ask_secret GITHUB_TOKEN "Paste the GitHub PAT:"
      write_env GITHUB_TOKEN "$GITHUB_TOKEN"
      _merge_mcp_server github "$(cat <<'JSON'
{"url":"https://api.githubcopilot.com/mcp/","headers":{"Authorization":"Bearer ${env:GITHUB_TOKEN}"}}
JSON
)"
      _write_tracker_md github "$ASK_TRACKER_URL"
      ;;
    gitlab)
      prefill="https://gitlab.com"
      if [[ "$remote" == *gitlab* ]]; then
        prefill="$remote"
        prefill="${prefill%%/*}"
        # remote may be https://gitlab.com/group/repo — keep origin host
        if [[ "$remote" =~ ^(https://[^/]+) ]]; then
          prefill="${BASH_REMATCH[1]}"
        fi
      fi
      say "Prefill: $prefill"
      note "GitLab official MCP uses browser OAuth. No PAT is stored in .ask.env."
      ask ASK_TRACKER_URL "GitLab instance URL (Enter uses prefill if empty and none saved):"
      [[ -z "$ASK_TRACKER_URL" ]] && ASK_TRACKER_URL="$prefill"
      ASK_TRACKER_URL="${ASK_TRACKER_URL%/}"
      write_env ASK_TRACKER "$ASK_TRACKER"
      write_env ASK_TRACKER_URL "$ASK_TRACKER_URL"
      gitlab_mcp="${ASK_TRACKER_URL}/api/v4/mcp"
      open_url "$gitlab_mcp"
      step "After Cursor reloads, approve the GitLab OAuth prompt in the browser."
      _merge_mcp_server GitLab "$(printf '{"type":"http","url":%s}' "$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$gitlab_mcp")")"
      _write_tracker_md gitlab "$ASK_TRACKER_URL"
      ;;
  esac
fi

stage "Memory MCP"
say "Optional. Default on this machine: codebase-memory-mcp."
say "1) codebase-memory-mcp  2) skip  3) custom command"
ask MEMORY_CHOICE "Choice [1/2/3]:"
case "${MEMORY_CHOICE:-1}" in
  2|skip|none)
    note "Skipped memory MCP."
    ;;
  3|custom)
    ask MEMORY_CMD "Command for the memory MCP:"
    if [[ -n "${MEMORY_CMD:-}" ]]; then
      spec="$(python3 -c 'import json,sys; print(json.dumps({"command": sys.argv[1]}))' "$MEMORY_CMD")"
      _merge_mcp_server memory-mcp "$spec"
    fi
    ;;
  *)
    default_mem="${HOME}/.local/bin/codebase-memory-mcp"
    ask MEMORY_PATH "Path to codebase-memory-mcp (Enter uses default if empty):"
    [[ -z "${MEMORY_PATH:-}" ]] && MEMORY_PATH="$default_mem"
    spec="$(python3 -c 'import json,sys; print(json.dumps({"command": sys.argv[1]}))' "$MEMORY_PATH")"
    _merge_mcp_server codebase-memory-mcp "$spec"
    ;;
esac

stage "Current issue context"
say "Epic/story stay in gitignored .ask/tracker-context.md. Edit them anytime."
_write_tracker_context
ask ASK_EPIC "Current epic (optional):"
ask ASK_STORY "Current story (optional):"
if [[ -n "${ASK_EPIC:-}" || -n "${ASK_STORY:-}" ]]; then
  cat > "$ASK_ROOT/.ask/tracker-context.md" <<EOF
# Current issue (local; gitignored)

- **epic:** ${ASK_EPIC:-}
- **story:** ${ASK_STORY:-}
EOF
  note "updated .ask/tracker-context.md"
fi

stage "OpenSpec CLI"
say "Install the pinned OpenSpec CLI under ~/.local."
say "Skipped with a warning if node or npm is missing. Tracker setup still finishes."
set +e
"$ASK_ROOT/_ask/scripts/ensure-openspec.sh"
os_code=$?
set -e
if [[ "$os_code" -eq 0 ]]; then
  note "OpenSpec CLI matches the pin at \$HOME/.local/bin/openspec"
else
  warn "OpenSpec CLI not installed (exit ${os_code}). Marked-pilot gates still fail closed."
fi

note "Restart Cursor (or toggle MCP servers) so new stubs load."
note "Source .ask.env in your shell before launching Cursor if you set tokens."
finish
