#!/usr/bin/env bash
# Generate Cursor-honored projections from .agents/ask/stages (fallback: _ask/agents).
# Merges .agents/ask.local/stages/<stage>.md then _ask/agents/<stage>.local.md.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
OUT_SKILLS=".cursor/skills"
OUT_CMDS=".cursor/commands"
mkdir -p "$OUT_SKILLS" "$OUT_CMDS"

if [[ -d .agents/ask/stages ]]; then
  STAGE_DIR=".agents/ask/stages"
  MARKER="# Generated by sync-cursor-binding.sh — do not hand-edit; edit .agents/ask/stages instead."
  SRC_LABEL=".agents/ask/stages"
else
  STAGE_DIR="_ask/agents"
  MARKER="# Generated by sync-cursor-binding.sh — do not hand-edit; edit _ask/agents instead."
  SRC_LABEL="_ask/agents"
fi

for src in "$STAGE_DIR"/[0-9][0-9]-*.md; do
  [[ -f "$src" ]] || continue
  base="$(basename "$src" .md)"
  [[ "$base" == *.local ]] && continue
  local_overlay=".agents/ask.local/stages/${base}.md"
  if [[ ! -f "$local_overlay" ]]; then
    local_overlay="_ask/agents/${base}.local.md"
  fi
  body="$(cat "$src")"
  if [[ -f "$local_overlay" ]]; then
    body="${body}"$'\n\n'"# Local overlay ($(basename "$local_overlay"))"$'\n\n'"$(cat "$local_overlay")"
  fi
  skill_dir="${OUT_SKILLS}/kit-${base}"
  mkdir -p "$skill_dir"
  {
    echo "---"
    echo "name: kit-${base}"
    echo "description: Kit protocol stage ${base}. Generated from ${SRC_LABEL}/${base}.md"
    echo "---"
    echo
    echo "$MARKER"
    echo
    echo "$body"
  } > "${skill_dir}/SKILL.md"

  {
    echo "$MARKER"
    echo
    echo "$body"
  } > "${OUT_CMDS}/${base}.md"
done

for src in _ask/cursor-commands/*.md; do
  [[ -f "$src" ]] || continue
  cp "$src" "${OUT_CMDS}/$(basename "$src")"
done

python3 "$ROOT/_ask/scripts/sync-runtime-agents.py"

echo "sync-cursor-binding: generated projections under ${OUT_SKILLS} and ${OUT_CMDS}"
