#!/usr/bin/env python3
"""Project ASK stages into Codex's repository skill directory."""
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MARKER = '# Generated by sync-cursor-binding.sh — do not hand-edit; edit '


def update_ignore():
    path = ROOT / '.gitignore'
    lines = path.read_text().splitlines() if path.exists() else []
    legacy = {'.agents/skills/', '/.agents/skills/', '.agents/skills', '/.agents/skills'}
    rules = ['.agents/skills/*', '!.agents/skills/kit-*/']
    comment = '# Prepared skills; ASK kit-* projections are committed'
    lines = [line for line in lines if line.strip() not in legacy | set(rules) | {comment}]
    path.write_text('\n'.join(lines).rstrip() + '\n\n# Prepared skills; ASK kit-* projections are committed\n' + '\n'.join(rules) + '\n')


def main():
    if '--update-ignore' in sys.argv:
        update_ignore()
        return
    skills = ROOT / '.agents/skills'
    if skills.is_symlink():
        raise ValueError('refuse symlink .agents/skills')
    stages = ROOT / '.agents/ask/stages'
    if not stages.is_dir():
        stages = ROOT / '_ask/agents'
    names = {'kit-' + p.stem for p in stages.glob('[0-9][0-9]-*.md') if not p.stem.endswith('.local')}
    if '--check-trackability' in sys.argv:
        for name in sorted(names):
            path = Path('.agents/skills') / name / 'SKILL.md'
            if not (ROOT / path).is_file():
                raise ValueError('missing generated skill: ' + str(path))
            check = subprocess.run(
                ['git', 'check-ignore', '--no-index', '-q', str(path)],
                cwd=ROOT, capture_output=True, text=True,
            )
            if check.returncode == 0:
                detail = subprocess.run(
                    ['git', 'check-ignore', '--no-index', '-v', str(path)],
                    cwd=ROOT, capture_output=True, text=True, check=True,
                ).stdout.strip()
                raise ValueError('generated skill not trackable; blocking rule: ' + detail)
            if check.returncode != 1:
                raise ValueError('cannot check Git trackability: ' + check.stderr.strip())
        return
    # Validate every reserved child before any output is written or removed.
    owned = []
    for child in sorted(skills.glob('kit-*')):
        skill = child / 'SKILL.md'
        if child.is_symlink() or not child.is_dir() or skill.is_symlink() or not skill.is_file():
            raise ValueError('reserved skill collision: ' + str(child))
        text = skill.read_text()
        if not any(line.startswith(MARKER) for line in text.splitlines()):
            raise ValueError('unmarked reserved skill collision: ' + str(child))
        if set(child.iterdir()) != {skill}:
            raise ValueError('unexpected contents in generated skill: ' + str(child))
        owned.append(child)
    if '--check' in sys.argv:
        return
    for child in owned:
        if child.name not in names:
            shutil.rmtree(child)
    for name in sorted(names):
        dest = skills / name
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / '.cursor/skills' / name / 'SKILL.md', dest / 'SKILL.md')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError) as exc:
        print('sync-codex-skills: ' + str(exc), file=sys.stderr)
        sys.exit(1)
