#!/usr/bin/env bash
# Generate Cursor-honored projections from _ask/agents/*.md
# Merges optional _ask/agents/<stage>.local.md overlays.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
OUT_SKILLS=".cursor/skills"
OUT_CMDS=".cursor/commands"
mkdir -p "$OUT_SKILLS" "$OUT_CMDS"

# marker so regen is idempotent
MARKER="# Generated by sync-cursor-binding.sh — do not hand-edit; edit _ask/agents instead."

for src in _ask/agents/[0-9][0-9]-*.md; do
  [[ -f "$src" ]] || continue
  base="$(basename "$src" .md)"
  # skip local overlays as sources
  [[ "$base" == *.local ]] && continue
  local_overlay="_ask/agents/${base}.local.md"
  body="$(cat "$src")"
  if [[ -f "$local_overlay" ]]; then
    body="${body}"$'\n\n'"# Local overlay (${base}.local.md)"$'\n\n'"$(cat "$local_overlay")"
  fi
  skill_dir="${OUT_SKILLS}/kit-${base}"
  mkdir -p "$skill_dir"
  # SKILL.md front matter name must match folder
  {
    echo "---"
    echo "name: kit-${base}"
    echo "description: Kit protocol stage ${base}. Generated from _ask/agents/${base}.md"
    echo "---"
    echo
    echo "$MARKER"
    echo
    echo "$body"
  } > "${skill_dir}/SKILL.md"

  # slash-command projection
  {
    echo "$MARKER"
    echo
    echo "$body"
  } > "${OUT_CMDS}/${base}.md"
done

# Session-mode commands (not stage projections)
for src in _ask/cursor-commands/*.md; do
  [[ -f "$src" ]] || continue
  cp "$src" "${OUT_CMDS}/$(basename "$src")"
done

echo "sync-cursor-binding: generated projections under ${OUT_SKILLS} and ${OUT_CMDS}"
