---
name: {{name}}
description: {{description}}
model: {{model}}
{{readonly_line}}---

# Generated by ./ask sync from .agents/ask/bindings/. Do not hand-edit.

Runtime: {{runtime}}
Protocol: `.agents/ask/stages/{{stage}}.md`

Follow that protocol file. Resolve slugs from `.agents/ask/bindings/` (work overlay, env, consumer map, defaults, this runtime table). Do not close Grill or Accept in this child; return output to the parent chat.
