# Specification: Engineering Model and local workbench

Status: CURRENT specification, revision 3. The model and initial workbench are implemented; the human requested a comprehensive UI redesign and a planning-only stop. Canonical observable criteria: adjacent JSON contract. Original intent and confirmation remain historical authority for the foundation. The current user-directed delta is `work/structured-agentic-environment/spec-change-workbench-redesign.md`; interaction details are in `work/structured-agentic-environment/workbench-design.md`. This revision requires independent contract review and pinning before implementation.

## Authority and scope

A revisioned `work/<id>/engineering-model.json` owns broader engineering definitions and references. Existing canonical criterion JSON, accepted test plans, code, coordinator review/execution evidence and inner-loop runtime remain their own authorities. The model stores references, not competing Given/When/Then or test outcomes. Markdown, machine context and UI are projections. There is no editable “verified” field or UI shortcut to existing acceptance/integration gates.

The first pilot is this workstream, using harness-review as an actual read-only traceability example plus an explicitly labeled pilot future-work decision. Model creation/validation and controlled editing must work before UI implementation starts. One local cooperating developer; Git remains the change review/history mechanism. No authenticated authorization or multi-host concurrency guarantee is claimed.

## Definition contract

Schema `ask-engineering-model/v1`: work_id, positive integer revision, nodes and edges. Stable node IDs are unique nonempty slugs within the model. Node types: intent, requirement, feature, story, scenario, decision, assumption, task, implementation, test, test_run, risk, evidence. Every node has a nonempty title and a type-specific definition lifecycle. Generic nodes use draft/active/retired; decisions open/resolved/retired; assumptions unverified/confirmed/rejected/retired; tasks planned/active/done/retired; risks open/mitigated/retired. Definition lifecycle never asserts execution outcome.

`contains` expresses intent→feature/requirement/task/decision/assumption/risk, feature→story/requirement/scenario/task/decision, story→scenario/task/decision, requirement→scenario. Exactly one intent is required. Every non-draft feature/requirement/story/scenario/task has exactly one legal parent. Each test covers at least one scenario via test→scenario `covers`. Implementation→scenario/task `implements`; test_run→test `executes`; evidence→test/test_run `supports`. `depends_on` is legal from task to task/decision/assumption and decision to decision/feature/requirement/scenario/assumption. Reject broken references, illegal types/edges, duplicates, containment/dependency cycles, contradictory lifecycle/resolution and unexpected fields. Standalone validation reports precise stable codes and IDs, including malformed JSON/schema/field types; it never mutates.

Active requirement/scenario references select an existing canonical criterion; tests select an existing test-plan case. Implementation references are safe repository-relative source paths, optionally symbols. Evidence/run references are safe repository-relative JSON paths; unavailable runtime evidence is visible missing evidence, not a malformed engineering definition. Resolve paths inside the repository, including symlink checks. Reference-only test/evidence nodes carry no mutable outcome. Draft requirement/scenario nodes may await a canonical reference.

Decisions have at least two unique option IDs/labels. A resolution records option_id, nonempty actor/rationale, UTC timestamp. Resolved state requires a valid resolution; open state has none. History preserves prior resolutions/reopening/invalidation. Actor attribution is cooperative local input, not authentication.

## Semantic editing interface

One shared module provides load/validate, snapshot/project and guarded mutation. Commands add_node, add_edge, remove_edge, resolve_decision, reopen_decision and revise_node cover this slice; change_batch stages coordinated commands/spec-file changes as one action. Node-plus-required-parent/coverage edges can be created atomically; a node need not be published orphaned first. Stable IDs and node types are immutable. Revisions may change title/description/reference and declared type-specific lifecycle; decision options may change only while open. Resolve/reopen/retire use explicit attributable decision operations, with old choices/options retained in history; no raw resolved-state edit bypasses them.

Editing a dependency, resolving/reopening/changing an upstream decision, or adding/removing a dependency reopens affected transitively dependent resolved decisions, preserving prior resolution and reason in history. Planned/active tasks are blocked by open/retired decisions, unverified/rejected/retired assumptions or unfinished/retired task prerequisites. Only resolved decisions, confirmed assumptions and done tasks satisfy their respective prerequisites. Retiring an object never silently satisfies its dependents. A declared done task is not proof of behavioral completion; reopening work is explicit and existing evidence/acceptance authority remains unchanged.

Every mutation goes through the document-state action guard below. Expected state identity includes the model and referenced specification/definition inputs, not just the model-file digest. Valid edits increment the model revision exactly once. Invalid commands, missing attribution or stale inputs do not publish. CLI and UI call this shared interface. Changes remain visible Git changes; the app neither commits nor spawns work.

## Document-state action guard

Before every state-changing engineering action, capture and validate the current definition/reference snapshot. Failure stops before the action is invoked. Stage the action's candidate edits without exposing them to consumers; validate the resulting complete state after the action. Recheck the base input identities, then publish one immutable validated snapshot/generation. Invalid results or concurrent changes prevent publication and preserve the last stable generation. Multi-file actions must not expose partially applied specifications; atomic replacement of individual files alone is not a multi-file transaction.

The validation input set includes the Engineering Model, canonical specification definitions, linked criteria/test definitions and all relevant reference targets. A referenced specification edit/create/delete invalidates the current result even if the model file is unchanged. Bind validation identity to input paths/content, dependency discovery and validator rule version; timestamps alone are insufficient. Readers use bytes from the validated snapshot, not mutable files reread after validation. State-changing actions include semantic spec/model edits and workflow action admission; this guard adds no replacement test-completion or human-approval policy.

Run validation after every specification save/change through the shared change path or document-layer change observer. Startup plus consumer/action entry freshness checks cover external writes and missed observer events. Unmanaged editor/tool changes cannot be made transactional by wishful enforcement: until validated they are untrusted working state and must not become actionable UI/agent input. The last stable snapshot may remain visible only explicitly labeled last-validated/not editable; current actions fail closed. Repair/import is an explicit draft operation, not automatic UI repair or ordinary work on a broken base.

The validator is independently runnable and is the single implementation of graph/reference/lifecycle rules. UI code trusts its validated snapshot contract. User input/action conflicts and external evidence freshness remain separate runtime concerns. Initial import validates existing state before admitting it; there is no bootstrap shortcut treating an invalid initial document as stable.

The adopted pilot's managed public entry points are model/spec change_batch/edit, decision resolve/reopen/revise operations through that edit path, and workflow admission for implementation/review/verification/integration/acceptance. Proposed CLI surfaces are `./ask model edit|admit|validate|watch|show|ui`; these are planned interfaces, not existing commands. Wire existing `inner-loop run/resume` and its integration path, `verify`, `record-result --result pass` and acceptance checking to the same guard for the adopted workstream. Coordinator-managed review/implementation admission uses that interface as well. Readers/show/UI use document admission but do not create a new semantic change. Raw editor saves use the observer plus freshness fallback, not a second mutator. Tests must demonstrate successful pre-validation → one action → post-validation → one publication, with input/result identities, and prove each public state-changing entry point cannot bypass the shared guard. Other workstreams retain existing policy; no unadopted state is labeled validated.

## Performance and implementation freedom

Validator implementation is language-neutral. Reuse suitable existing fast tooling; a lower-level implementation is allowed. Select after a bounded benchmark of actual repository inputs plus deterministic 100/1,000/10,000-node graphs with recorded edge/file counts, invalid-link/cycle variants, cold/warm runs and the complete pre/post action path. Record hardware/tool versions, p50/p95 latency, peak memory and parse/I/O/graph/publication costs. Language labels alone are not evidence of speed. No numerical latency target or performance gain has been agreed or measured yet.

Keep a stable machine interface and diagnostics regardless of implementation. Incremental/cached validation is permitted only when it agrees with full validation, invalidates on referenced input/rule changes and preserves global uniqueness/cardinality/cycle checks. No cache or alternative backend may skip the before/after guard. Full validation remains available for parity tests, startup and final verification. Implementation selection must retain the existing traceability test-driver contract or receive a reviewed binding amendment before implementation.

## Projections and evidence

Machine JSON and deterministic Markdown expose identical object IDs, hierarchy, references, unresolved decisions, dependency reasons and derived task readiness. Projections preserve source/model digests and evidence revision identity. Scenario inspection reads canonical Given/When/Then and planned assertions/cases, source references, required test types, actual retained outcomes and provenance. A declared link is explicitly not proof of behavior.

The read-only evidence adapter reuses a shared nonmutating path through the existing traceability binding and completion checks rather than trusting a cached pass field. This includes static receipt/CheckPlan identity, pinned runner identity, static and behavior log digests, accepted authority, semantic review and actual cases. Extract read-only evaluation from the current report-writing completion operation without weakening normal command checks; do not reimplement a reduced subset in the UI. Historical checks bind to the inspected candidate's inputs, not unrelated current files. Missing local accepted ref, missing/malformed reports, changed logs/bindings or stale contracts are visible unavailable/invalid evidence. Historical candidate evidence is explicitly historical relative to the inspected checkout; it cannot establish current completion. Inspection must not write completion files, advance refs, run tests or call acceptance. No new completion policy is introduced.

## Interactive UI

The workbench presents Epic → Story → Scenario → Task → Test → Result / Evidence, preserving many-to-many relationships rather than treating this as exclusive containment. An Epic labels the existing intent/feature presentation; it adds no new model type. The current branch's active work opens by default. Overview explains purpose, scenarios, task states, known results and actionable attention. One connected hierarchy with a selected detail panel is the primary experience. Story and scenario details, task master-detail, selected test/source/result detail, and contextual attention are levels of that experience. Task/test/status lists are optional filters of the same hierarchy rather than separate primary tabs. Preserve recorded story membership; explicitly show missing story records without inventing them. Source, logs and technical evidence load on request. Existing generic objects remain available as secondary detail where useful.

Join real task graph metadata and reviewed task scopes with canonical scenario/test references and actual runtime task evidence. Each task has a meaningful outcome, dependencies, owned paths, scoped tests and completion evidence. Missing historical breakdown remains explicit. Declared task lifecycle, readiness, execution/integration and proved completion are distinct. Every summary count opens the corresponding records. Decisions show the question, options, context and known dependent work, with actor/rationale required for guarded resolution.

Inventory comes from local live refs and default-branch archive semantics, including works without a pilot Engineering Model. Distinguish checked-out branch, selected work and inspected source. Other branches/revisions are read through immutable committed snapshots without checkout/ref changes, with consistent model/test/source versions and original evidence authority. Historical and cross-branch browsing is read-only. Missing models, local authority or sources are visible limitations; there is no automatic migration.

The document layer remains the sole validator/admission/guard. Editable decisions exist only in the active checkout's admitted current work. Preserve the full originally displayed state identity across navigation/reruns; concurrent edits require explicit refresh, and stale/invalid submissions leave bytes unchanged. Historical browsing cannot publish or resolve decisions. Actual test outcomes are distinct from workstream verification, historical/stale applicability and missing evidence. Source is selected by full qualified test selector at its selected revision. Show actual failure output and recorded run time/duration where present. Technical details explain commit, contract, snapshot and run identifiers with useful copyable values and existing commands; raw JSON and hashes are collapsed initially.

Apply the pinned frontend-design skill and Streamlit references. Use a coherent theme, compact navigation, responsive list-detail layout, readable labels, keyboard focus and non-color status indicators. Initial Overview does not parse test source or scan evidence. Cache only identity-bound reads; refresh and integrity changes invalidate cached views, and mutations always recheck admission. Measure initial load and common interactions. Proposed pilot budgets and benchmark methodology are specified in the design; record actual misses and justify a technology amendment with evidence before replacing Streamlit. Core CLI remains independent of UI dependencies. Arbitrary source editing, production deployment and automatic test execution/acceptance remain outside scope.

## Observable acceptance

- EM-001: Standalone validation accepts representative broad typed models and rejects malformed fields, duplicate/broken identities/references, illegal relationships/cardinality, cycles and lifecycle conflicts with precise diagnostics.
- EM-002: Shared semantic mutation persists attributable decisions, propagates blockers/invalidation and history, increments revisions; stale/invalid edits and concurrent stale writers preserve data.
- EM-003: Read-only scenario/evidence inspection reuses current authorities, shows actual assertions/outcomes/provenance, differentiates historical/missing/invalid evidence, and cannot turn a link or tampered pass field into current completion.
- EM-004: Public CLI validation, JSON/Markdown projections and decision-edit journey share the same model and digest; CLI errors are useful and nonmutating.
- EM-005: UI consumes a validated snapshot and navigates work/scenario to canonical assertion/test/evidence detail with honest missing/historical evidence states, without domain-validation/repair logic.
- EM-006: UI attention/decision journey persists a reasoned choice and derived task change across reload; stale forms reject concurrent changes and invalid submissions do not write.
- EM-007: The shared document layer enforces current-state validation before every state-changing action and result validation afterward, revalidates every spec change, invalidates referenced-input/cache identities, blocks invalid/stale admission and publishes only complete stable snapshots.

- EM-008: Meaningful titles and one connected hierarchy preserve recorded story membership and many-to-many links; shared tests are deduplicated and missing stories/links remain visible without invented containment The opening overview explains purpose, scenario coverage, task status, known test results and attention without expanding all source or raw JSON
- EM-009: The current branch work opens by default; checkout, selected work and inspected source are distinct Committed cross-branch inspection reads one validated revision and its matching source/evidence without switching checkout, changing refs or enabling semantic edits; unavailable artifacts are explained
- EM-010: Planned, active, blocked and completed tasks are discoverable with descriptions, dependencies, scenarios, tests and recorded implementation evidence Every summary count filters the same hierarchy to its exact records; blockers name their cause and decisions show available choices and guarded resolution No missing history or declared done lifecycle is promoted to verified completion
- EM-011: Source is syntax highlighted and corresponds to the selected qualified test and revision; results match work, test, run and contract identities Passed, failed, not run, unavailable, stale, historical, skipped and runtime-error states preserve actual meaning; missing time and duration are explicit Debug identifiers remain collapsed initially and have explanations, copyable values and usable artifact links or commands; execution pass remains distinct from incomplete verification history
- EM-012: Responsive list-detail navigation, accessible labels/focus/contrast and non-color status text allow the primary inspection and decision journeys Initial Overview performs no test-source or evidence scan; selected detail loads lazily and cache refresh or changed inputs cannot hide stale or tampered evidence Pilot latency budgets are measured with documented samples and misses; a technology replacement requires observed limitations and a reviewed amendment

## E2E

Applies. Guard journey verifies pre-validation → action → post-validation → publication and failure isolation, including external/linked spec edits. CLI journey, UI integration via Streamlit AppTest and real temporary browser E2E cover scenario inspection, persisted decision→unblock→reload and stale-form protection. Broken-document cases belong to document admission/validator tests, not UI business logic. Browser/server and data are test-owned, local, reset by teardown; never mutate the committed pilot from tests. Required types/cases are in the independently challenged test plan. Full repository Verify and candidate-bound independent semantic review remain mandatory after implementation. Planning checks establish contract consistency only, not feature behavior or comparative usability/productivity.
